### PR TITLE
 #66 ES Operator doesn't scale-down to its boundary

### LINKED ISSUE #66: ES Operator doesn't scale-down to its boundary
## Expected Behavior

When I specify `maxShardsPerNode: X` I would assume that the ES Operator would still allow scaling to that X shards per node target, not stop before.

## Actual Behavior

The boundary is seen non-inclusive, which means we don't save as much cost as we could.

## Steps to Reproduce the Problem

  1. Create an EDS with 4 maxReplicas: 4, minReplicas: 3, maxShardsPerNode: 40
  1. Allocate 5 indices, with 1 index replica, and 12 primaries. (= 5*2*12 = 120 shards, 30 shards per node)
  1. Assuming the issue wouldn't exist, the EDS would eventually scale down to 3 nodes (= 120/3 = 40 shards per node)

### PR DESCRIPTION
**Pull request by otrosien**
Closes #66

### CODE REVIEW

File: operator/autoscaler.go [hunk 1]
```diff
@@ -369,3 +369,4 @@ func (as *AutoScaler) calculateScalingDirection(oldNodeReplicas, newNodeReplicas
 	}
 	return NONE
 }
+
```
Comment (golangcibot) [inline operator/autoscaler.go]: File is not `goimports`-ed (from `goimports`)

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:
