### PR TITLE
 #55 Race condition for exclude._ip setting

### LINKED ISSUE #55: Race condition for exclude._ip setting
## Expected Behavior

Scaling down should work, even if two stacks get scaled down simultaneously.

## Actual Behavior

Only the last IP gets persisted in the exclude._ip setting, and as such only one node gets drained correctly. The reason is that `excludePodIP` is not atomic, but needs to call ES to retrieve the current exclude list, and then update it.

## Steps to Reproduce the Problem

  1. create two EDS joining the same cluster
  1. let them scale down simultaneously
  1. inspect the exclude._ip cluster setting, it might contain only one IP instead of two

### PR DESCRIPTION
**Pull request by otrosien**
Introduces a mutex to avoid race of exclude ip setting, also periodically check if the IP exclusion is still set on the cluster.
 
Fixes #55

### CODE REVIEW

File: operator/es_client.go [hunk 1]
```diff
@@ -200,33 +201,46 @@ func (c *ESClient) getClusterSettings() (*ESSettings, error) {
...
+		for _, ip := range ips {
+			if ip == podIP {
+				foundPodIP = true
+				break
+			}
+		}
+		if !foundPodIP {
+			ips = append(ips, podIP)
+			sort.Strings(ips)
+			err = c.setExcludeIPs(strings.Join(ips, ","))
```
Comment (golangcibot) [inline operator/es_client.go]: ineffectual assignment to `err` (from `ineffassign`)

**Comment by otrosien** [comment]
WIP.. may need a channel instead

File: operator/es_client.go [hunk 2]
```diff
@@ -26,6 +27,7 @@ var (
 // ESClient is a pod drainer which can drain data from Elasticsearch pods.
 type ESClient struct {
 	Endpoint *url.URL
+	mux sync.Mutex
```
Comment (golangcibot) [inline operator/es_client.go]: File is not `goimports`-ed (from `goimports`)

**Comment by otrosien** [comment]
ready for review

File: operator/es_client.go [hunk 3]
```diff
@@ -292,6 +300,14 @@ func (c *ESClient) waitForEmptyEsNode(ctx context.Context, pod *v1.Pod) error {
 					}
 				}
 				c.logger().Infof("Found %d remaining shards on %s/%s (%s)", remainingShards, pod.Namespace, pod.Name, podIP)
+
+				// make sure the IP is still excluded, this could have been updated in the meantime.
+				if remainingShards > 0 {
+					err = c.excludePodIP(pod)
```
Comment (otrosien) [inline operator/es_client.go]: we could also abort the retry after some time. There could be valid reasons why ES wouldn't relocate all data away from the node. For example if no other node is eligible for taking the shards.

Comment (otrosien) [reply operator/es_client.go]: (but personally, I prefer the repeating of excludePodIP here)

**Comment by njuettner** [comment]
👍

**Comment by otrosien** [comment]
👍
